version: 0.2

phases:
  build:
    commands:
      - aws s3 sync . s3://startpage.pinebeltpc.com --delete --exclude ".git/*" --exclude "buildspec.yml" --exclude "README.md" --exclude "LICENSE"
      - aws cloudfront create-invalidation --distribution-id E159WLJOB8SI5S --paths "/*"
