version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
      commands:
      - aws s3 sync . s3://mq-my-static-bucket --delete
  build:
    commands:
      - php --version
artifacts:
  files:
    -  README.md
    -  LICENSE

